import java.io.File

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

fun read(path: String): String =
    object {}.javaClass.getResource(path)!!.readText()

fun main() {
    //day1()
    //day2()
    day3()
}
